#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width	0
bspc config windows_gap		0

bspc config split_ratio		0.48
bspc config borderless_monocle	true
bspc config gapless_monocle		true

bspc rule -a subl desktop=^1 follow=on
bspc rule -a firefox desktop=^2 follow=on
bspc rule -a subl desktop=^3 follow=on
bspc rule -a atril desktop=^4 follow=on
bspc rule -a notion desktop=^5 follow=on
bspc rule -a thunar desktop=^6 follow=on
bspc rule -a spotify desktop=^7 follow=on

feh --bg-scale /home/denis/Pictures/moon-dark-night-clouds-602960522.jpg
picom &
~/.config/polybar/launch.sh
dunst &
